import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { headers } from "next/headers";
import ContextProvider from "@/providers/AppkitProvider";


const clashDisplay = localFont({
  src: [
    {
      path: "../public/fonts/ClashDisplay-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/ClashDisplay-Regular.otf", 
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/ClashDisplay-Bold.otf",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-clash-display",
});

const ceraPro = localFont({
  src: [
    {
      path: "../public/fonts/CeraPro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/CeraPro-Medium.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/CeraPro-Bold.otf",
      style: "bold",
    },
  ],
  variable: "--font-cera-pro",
});

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headersObj = await headers();
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en">
      <body className={`${ceraPro.variable} ${outfit.className} ${clashDisplay.variable} font- antialiased`}>
      <ContextProvider cookies={cookies}>{children}</ContextProvider>
      </body>
    </html>
  );
}
